export { HomePage } from './HomePage'
export { SignUpPage } from './SignUpPage'
export { SignInPage } from './SignInPage'
export { EditProfilePage } from './EditProfilePage'
export { MoviesPage } from './MoviesPage'
export { SeriesPage } from './SeriesPage'
export { NotFoundPage } from './NotFoundPage'
export { OtherUserProfilePage } from './OtherUserProfilePage'
